### ISSUE TITLE
Hello, I'm trying to create bartib file and I get this error.

### ISSUE THREAD

**Issue by hanylovescode** [nikolassv/bartib#17]
```
bartib -f ~/Users/username/bartib_logger.bartib report
Error: Could not read from file: /Users/username/bartib_logger.bartib

Caused by:
    No such file or directory (os error 2)
```
1. I have created bartib_logger.bartib file in the home directory

**Comment by nikolassv** [comment]
Hi, the file path does not look right to me. On ..nix systems the ~ normally denotes your users home path. So, a path like `~/Users/username` looks a little strange. What kind of system are you working on? Does `cat ~/Users/username/bartib_logger.bartib` work?

**Comment by Shok1989** [comment]
Hi! I have the same issue on my MacOS Ventura. I created the file and used a correct command, but Bartib just can't read from file =(

bartib start -d test_task -p test                                                                                                            ✔  00:18:48 
Started activity: "test_task" (test) at 2023-07-10 00:19
Error: Could not write to file: /home/igor/bartib_logger.bartib

Caused by:
    No such file or directory (os error 2)

**Comment by nikolassv** [comment]
Hi, I am not sure what might cause this error on your system. It looks like the directory for the file does not exists. What is the full path to your home directory (`echo $HOME`)? On mac the user home directories are normally inside a path `/Users`, so perhaps the right file path would be: `/Users/igor/bartib_logger.bartib`?
