### ISSUE TITLE
What does "bartib" mean, if anything?

### ISSUE THREAD

**Issue by neezer** [nikolassv/bartib#35]
Does the name come from / mean anything? Just curious.

Love the software! Thanks!

**Comment by mbaneshi** [comment]
_Same question here!_

**Why does this matter?**
Well, understanding the philosophy behind words helps us remember them. I've aliased "bartib" as "time_track," and now I can recall it more easily. However, the challenge lies in effectively communicating with others.

Thank you for creating this amazing tool for CLI enthusiasts.

**Comment by nikolassv** [comment]
No problem, I don't mind you asking. When I started writing `bartib`, I imagined the white rabbit from Alice in Wonderland who is in a constant hurry and constantly looks at its watch. "bartib" is just an anagram of "rabbit", and I selected it because I didn't know any other CLI utility by that name and it is relatively short.

**Comment by mbaneshi** [comment]
interesting, I never forget it since now
