### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by simonsan** [nikolassv/bartib#50]
Hey there,
`bartib` inspired me to build https://github.com/pace-rs/pace because I felt my use case for tracking work and break times is not fulfilled by a lot of tools out there. I do see that you also spend a lot of time thinking about time management techniques. Earlier, you said you consider `bartib` to be feature-complete so I started implementing `pace` based on my own ideas and inspirational things from bartib, timetracking, vayu and work-break.

> Doing the same work should be discouraged. Working together should be applauded.

Based on that, I wanted to ask if you feel - despite your work on bartib - like joining the cause and help to implement `pace`. :) There is a discord link in the repository, if you want to discuss further, would be happy to see you there.

Cheers,
Simon

**Comment by nikolassv** [comment]
Thank you for bringing this project to my attention and the invitation to collaborate! This looks very promising and surely fills a gap those who do like to have more features in their time tracking than `bartib` can offer. I am unsure, whether I will be able to put much time into this, but I will have a look at it.

**Comment by simonsan** [comment]
I want to compliment you for the cleanliness of the layout of your report, something I didn't felt like wanting to spend too much time in (I saw you wrote a couple of LOC for that).

In pace I did it now like this with `tabled`, if you ever feel like contributing ... 😅 

![2024-03-08 02_14_31-activity_tracker rs (Working Tree) (activity_tracker rs) - pace - Rust Dev - VSC](https://github.com/nikolassv/bartib/assets/14062932/afb4bc44-ec91-4cc3-a986-9f2657a241d6)

One idea I want to follow up on is the reporting, as I want to minimize the effort on the review layout, I feel it's nice to ramp up effort on html templating, so people can create their own templates and pace fills it out. That might be great for billing templates etc.

**Comment by nikolassv** [comment]
yes, getting the report was quite a lot of work. When I wrote most of it, I also looked around for some existing table crates, but they either did not fulfill all my needs or they were too bloated for a simple cli application. That's why I decided to write my own solution. Surprisingly, the hardest part was getting word breaks right. I never assumed it would be so complicated. Eventually, I used [textwrap](https://github.com/mgeisler/textwrap) which does a nice job.

Formatting tables always comes with some edge cases that are imposible to get right, like a terminal width smaller than 10. Luckily, they rarely occur in real life, and I assume whoever uses such a narrow terminal has other problems than a suboptimal bartib report. You just have to decide which edge cases you support and which you ignore.

Something that really bothers me is that I was never able to accurately test bartib with non-latin charsets. I would like to know if the report is at least usable with chinese, korean or arabic letters.

I like the idea of giving people the possibility to use their own templates. That would help integrating it in other workflows. For bartib, I still like the Idea of machine readable output (like suggested in this issue: https://github.com/nikolassv/bartib/issues/21). Then you could pipe the output of bartib to some templating script. Unfortunately, this is not as simple to implement, as one would think, as in bartib as of today there is no real seperate viewing layer. I hope I would someday find the time to implement it.

**Comment by simonsan** [comment]
> I like the idea of giving people the possibility to use their own templates. That would help integrating it in other workflows. For bartib, I still like the Idea of machine readable output (like suggested in this issue: #21). Then you could pipe the output of bartib to some templating script. Unfortunately, this is not as simple to implement, as one would think, as in bartib as of today there is no real seperate viewing layer. I hope I would someday find the time to implement it.

Yes, I had the machine-readable output in mind, when I was writing the code from the beginning on, so I did it in the way, that `pace` is able to show/export the activity report in [`json` and other formats](https://github.com/pace-rs/pace/blob/main/crates/core/src/commands/review.rs#L100). I think HTML, Markdown, (and maybe even Plaintext, although that could be an export of the CLI output) will involve the templating engine. So I wonder if you couldn't shove everything in one struct as a `ReviewSummary` and serialize that as `json` for that issue, that you linked? Or how do you mean the part with the viewing layer?
